### ISSUE TITLE
"Raw" SCGI examples fail

### ISSUE THREAD

**Issue by adaptiveoptics** [supernovus/SCGI#12]
Thanks so much for the SCGI stuff!

Ran across an issue in the examples, both the text one and in the examples folder, for the "raw" SCGI server that's not doing PSGI. It looks like it wants PSGI regardless. ;)

Being access though a test/working nginx (works fine using SCGI with PSGI).

The SCGI server dies if you access it with the following complaint: (when started with :!PSGI as in the example which was tried both in the readme and example folder)

Starting raw SCGI server.
Cannot resolve caller encode-psgi-response(Str, :!nph); none of these signatures match:
    ($code, $headers, $body, Bool :$nph, :$protocol = "HTTP/1.0")
    ($p, Bool :$nph, :$protocol = "HTTP/1.0")
    (@response, Bool :$nph, :$protocol = "HTTP/1.0")
  in method send at /home/mark/.rakudobrew/moar-nom/install/share/perl6/site/sources/64EC9C87B6769EC9CF99A500C92FFB61EE711E87 (SCGI::Response) line 15
  in method send at /home/mark/.rakudobrew/moar-nom/install/share/perl6/site/sources/B4732BDAAF89B7F612E129EECBEDE2C26E34942F (SCGI::Connection) line 18
  in block  at tmp/foo line 16
  in block <unit> at tmp/foo line 7

**Comment by supernovus** [comment]
I will take a look when I have a chance. It's been a while since I worked on this code. Most commits lately have been from other people.

**Comment by adaptiveoptics** [comment]
Oh no hurry on my end! I was just passing along what I noticed.

**Comment by adaptiveoptics** [comment]
I fixed it - just adding the :!P6SGI flag in addition to the :!PSGI flag mentioned, fixes it.

**Comment by supernovus** [comment]
Thanks!
