### ISSUE TITLE
scgi: scgi: can't connect to server

### ISSUE THREAD

**Issue by softwareishappiness** [supernovus/SCGI#14]
Hi,

What could possibly be causing the following errors? Apache2 configuration is:

`SCGIMount /cgi/ 127.0.0.1:8118`

The Apache2 error log says:

`[Fri Mar 03 03:31:50.749687 2017] [:error] [pid 27714] (111)Connection refused: [client 98.203.61.46:47803] scgi: scgi: can't connect to server`

I am trying to run the following script so that it may receive Apache2 SCGI requests:

```
!/opt/rakudo-star/bin/perl6

  use SCGI;

  my $scgi = SCGI.new( :port(8118), :!PSGI );
  while (my $connection = $scgi.accept())
  {
    my $request = $connection.request;
    if $request.success
    {
      my $name = $request.env<QUERY_STRING> || 'world';
      my $return = "Hello $name\n";
      my $len = $return.encode.bytes;
      my $headers = "Content-Type: text/plain\nContent-Length: $len\n";
      $connection.send("$headers\n$return");
    }
    $connection.close;
  }

```
However the script isn't able to run instead it produces the following error:

```
Nothing given for new socket to connect or bind to
  in method connect at /opt/rakudo-star/share/perl6/site/sources/C11D891CD203B7B2D193DB72720B54EF97F16A39 (SCGI) line 22
  in method accept at /opt/rakudo-star/share/perl6/site/sources/C11D891CD203B7B2D193DB72720B54EF97F16A39 (SCGI) line 35
  in block <unit> at ./index.pl6 line 6

Actually thrown at:
  in method accept at /opt/rakudo-star/share/perl6/site/sources/C11D891CD203B7B2D193DB72720B54EF97F16A39 (SCGI) line 35
  in block <unit> at ./index.pl6 line 6
```

Thanks you for explaining what is happening or not happening.

Michael

**Comment by softwareishappiness** [comment]
Would it be possible to receive some feedback. I very much would like to use this module as a basis for a Perl6 web framework.

**Comment by supernovus** [comment]
I don't recommend using SCGI directly by itself. It's a fairly raw library (and it hasn't been updated in a long time, not that it usually requires much in the way of updates.)

I'd take a look at https://github.com/supernovus/perl6-web

That's meant as the primary library for doing any kind of web development with Perl 6 (it's offers a far better level of abstraction), and it supports a few backends (at least  SCGI, HTTP::Easy, FastCGI are supported from my memory.)

As for the error in question, it's one I have not seen, looking at the commit logs (I haven't maintained the library in a while) if you really want to use raw SCGI (really not recommended, use PSGI/P6SGI, or better yet, the library above which does all that for you) you'd need to change:

my $scgi = SCGI.new( :port(8118), :!PSGI );

to:

my $scgi = SCGI.new( :port(8118), :!PSGI, :!P6SGI );

Again, using an extremely low level library like SCGI directly is not recommended for any production development, but for testing purposes, that should work.
